services:
  - type: web
    name: mindalike-fraud-detection
    env: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn "main:app" --bind 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: LOG_LEVEL
        value: debug
    healthCheckPath: /
    autoDeploy: true
    routes:
      - type: rewrite
        source: /
        destination: /
    disk:
      name: logs
      mountPath: /logs
      sizeGB: 1
